---
- name: Collect facts on existing services
  service_facts:
  tags:
    - backup

- name: Ensure exist instance is stopped
  service:
    name: "{{ exist_instname }}"
    state: stopped
  when: exist_instname in services
  tags:
    - backup

- name: Backup installed exist instance
  become: true
  shell: "{{ exist_path }}/contrib/exist-filebased-backup.sh -M {{ exist_instname }} {{ exist_instuser }}"
  when:
    - exist_is_installed
    - exist_backup_previnstall
  tags:
    - backup
